version: '3.8'

services:
  krealty-api:
    container_name: krealty-api
    restart: always
    image: node:18.20.8
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/krealty
    working_dir: /usr/src/krealty
    environment:
      - PORT_API=3000
      - NODE_ENV=production
    networks:
      - monorepo-network
    #PRODUCTIONPORTS
    command: bash -c "npm install --include=dev && npm run build && npm run start:prod"

  krealty-batch:
    container_name: krealty-batch
    restart: unless-stopped
    image: node:18.20.8
    ports:
      - 3005:3005
    volumes:
      - ./:/usr/src/krealty
    working_dir: /usr/src/krealty
    environment:
      - PORT_BATCH=3005
      - NODE_ENV=production
    networks:
      - monorepo-network
    #PRODUCTION PORTS
    command: bash -c "npm install --include=dev && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
